linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - typecheck

linters-settings:
  errcheck:
    exclude-functions:
      - (io.Closer).Close
      - (net/http.ResponseWriter).Write

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unused
        - staticcheck
    - linters:
        - unused
      text: "k8opsBuiltinRoles|isCoreGroup|slackLogHelper"
    - linters:
        - staticcheck
      text: "SA1019"
    - path: groupversion_info\.go
      linters:
        - staticcheck
  max-issues-per-linter: 0
  max-same-issues: 0
