//go:build !ignore_autogenerated

/*
Copyright 2024 ggai.dev.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// --- DiagnosticReport ---

func (in *DiagnosticReport) DeepCopyInto(out *DiagnosticReport) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *DiagnosticReport) DeepCopy() *DiagnosticReport {
	if in == nil {
		return nil
	}
	out := new(DiagnosticReport)
	in.DeepCopyInto(out)
	return out
}

func (in *DiagnosticReport) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DiagnosticReportList) DeepCopyInto(out *DiagnosticReportList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiagnosticReport, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *DiagnosticReportList) DeepCopy() *DiagnosticReportList {
	if in == nil {
		return nil
	}
	out := new(DiagnosticReportList)
	in.DeepCopyInto(out)
	return out
}

func (in *DiagnosticReportList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *DiagnosticReportSpec) DeepCopyInto(out *DiagnosticReportSpec) {
	*out = *in
	in.Trigger.DeepCopyInto(&out.Trigger)
	if in.Analysis != nil {
		in, out := &in.Analysis, &out.Analysis
		*out = new(AnalysisSpec)
		**out = **in
	}
	if in.ResourceScope != nil {
		in, out := &in.ResourceScope, &out.ResourceScope
		*out = new(ResourceRef)
		**out = **in
	}
}

func (in *DiagnosticReportSpec) DeepCopy() *DiagnosticReportSpec {
	if in == nil {
		return nil
	}
	out := new(DiagnosticReportSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *DiagnosticReportStatus) DeepCopyInto(out *DiagnosticReportStatus) {
	*out = *in
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]Finding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.AnalyzedAt.DeepCopyInto(&out.AnalyzedAt)
	if in.AgentTrace != nil {
		in, out := &in.AgentTrace, &out.AgentTrace
		*out = make([]AgentStep, len(*in))
		copy(*out, *in)
	}
}

func (in *DiagnosticReportStatus) DeepCopy() *DiagnosticReportStatus {
	if in == nil {
		return nil
	}
	out := new(DiagnosticReportStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *DiagnosticTrigger) DeepCopyInto(out *DiagnosticTrigger) {
	*out = *in
	if in.ResourceRef != nil {
		in, out := &in.ResourceRef, &out.ResourceRef
		*out = new(ResourceRef)
		**out = **in
	}
}

func (in *DiagnosticTrigger) DeepCopy() *DiagnosticTrigger {
	if in == nil {
		return nil
	}
	out := new(DiagnosticTrigger)
	in.DeepCopyInto(out)
	return out
}

func (in *Finding) DeepCopyInto(out *Finding) {
	*out = *in
	if in.Evidence != nil {
		in, out := &in.Evidence, &out.Evidence
		*out = make([]Evidence, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SuggestedActions != nil {
		in, out := &in.SuggestedActions, &out.SuggestedActions
		*out = make([]SuggestedAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *Finding) DeepCopy() *Finding {
	if in == nil {
		return nil
	}
	out := new(Finding)
	in.DeepCopyInto(out)
	return out
}

func (in *Evidence) DeepCopyInto(out *Evidence) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

func (in *Evidence) DeepCopy() *Evidence {
	if in == nil {
		return nil
	}
	out := new(Evidence)
	in.DeepCopyInto(out)
	return out
}

func (in *SuggestedAction) DeepCopyInto(out *SuggestedAction) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(ResourceRef)
		**out = **in
	}
}

func (in *SuggestedAction) DeepCopy() *SuggestedAction {
	if in == nil {
		return nil
	}
	out := new(SuggestedAction)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentStep) DeepCopyInto(out *AgentStep) {
	*out = *in
}

func (in *AgentStep) DeepCopy() *AgentStep {
	if in == nil {
		return nil
	}
	out := new(AgentStep)
	in.DeepCopyInto(out)
	return out
}

// --- K8opsConfig ---

func (in *K8opsConfig) DeepCopyInto(out *K8opsConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *K8opsConfig) DeepCopy() *K8opsConfig {
	if in == nil {
		return nil
	}
	out := new(K8opsConfig)
	in.DeepCopyInto(out)
	return out
}

func (in *K8opsConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *K8opsConfigList) DeepCopyInto(out *K8opsConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K8opsConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *K8opsConfigList) DeepCopy() *K8opsConfigList {
	if in == nil {
		return nil
	}
	out := new(K8opsConfigList)
	in.DeepCopyInto(out)
	return out
}

func (in *K8opsConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *K8opsConfigSpec) DeepCopyInto(out *K8opsConfigSpec) {
	*out = *in
	in.Provider.DeepCopyInto(&out.Provider)
	in.Analysis.DeepCopyInto(&out.Analysis)
	in.AutoRemediation.DeepCopyInto(&out.AutoRemediation)
	in.Notifications.DeepCopyInto(&out.Notifications)
	in.Safety.DeepCopyInto(&out.Safety)
}

func (in *K8opsConfigSpec) DeepCopy() *K8opsConfigSpec {
	if in == nil {
		return nil
	}
	out := new(K8opsConfigSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *K8opsConfigStatus) DeepCopyInto(out *K8opsConfigStatus) {
	*out = *in
	in.LastSync.DeepCopyInto(&out.LastSync)
}

func (in *K8opsConfigStatus) DeepCopy() *K8opsConfigStatus {
	if in == nil {
		return nil
	}
	out := new(K8opsConfigStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *ProviderSpec) DeepCopyInto(out *ProviderSpec) {
	*out = *in
	if in.APIKeySecretRef != nil {
		in, out := &in.APIKeySecretRef, &out.APIKeySecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

func (in *ProviderSpec) DeepCopy() *ProviderSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

func (in *AutoRemediationSpec) DeepCopyInto(out *AutoRemediationSpec) {
	*out = *in
	if in.NamespaceAllowList != nil {
		in, out := &in.NamespaceAllowList, &out.NamespaceAllowList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NamespaceDenyList != nil {
		in, out := &in.NamespaceDenyList, &out.NamespaceDenyList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *AutoRemediationSpec) DeepCopy() *AutoRemediationSpec {
	if in == nil {
		return nil
	}
	out := new(AutoRemediationSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *NotificationSpec) DeepCopyInto(out *NotificationSpec) {
	*out = *in
	if in.Slack != nil {
		in, out := &in.Slack, &out.Slack
		*out = new(SlackNotification)
		(*in).DeepCopyInto(*out)
	}
}

func (in *NotificationSpec) DeepCopy() *NotificationSpec {
	if in == nil {
		return nil
	}
	out := new(NotificationSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SlackNotification) DeepCopyInto(out *SlackNotification) {
	*out = *in
	if in.WebhookSecretRef != nil {
		in, out := &in.WebhookSecretRef, &out.WebhookSecretRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

func (in *SlackNotification) DeepCopy() *SlackNotification {
	if in == nil {
		return nil
	}
	out := new(SlackNotification)
	in.DeepCopyInto(out)
	return out
}

func (in *AnalysisSpec) DeepCopyInto(out *AnalysisSpec) {
	*out = *in
}

func (in *AnalysisSpec) DeepCopy() *AnalysisSpec {
	if in == nil {
		return nil
	}
	out := new(AnalysisSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SafetySpec) DeepCopyInto(out *SafetySpec) {
	*out = *in
	if in.AllowedOperations != nil {
		in, out := &in.AllowedOperations, &out.AllowedOperations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DeniedOperations != nil {
		in, out := &in.DeniedOperations, &out.DeniedOperations
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ProtectedResources != nil {
		in, out := &in.ProtectedResources, &out.ProtectedResources
		*out = make([]ResourceRef, len(*in))
		copy(*out, *in)
	}
}

func (in *SafetySpec) DeepCopy() *SafetySpec {
	if in == nil {
		return nil
	}
	out := new(SafetySpec)
	in.DeepCopyInto(out)
	return out
}

func (in *ResourceRef) DeepCopyInto(out *ResourceRef) {
	*out = *in
}

func (in *ResourceRef) DeepCopy() *ResourceRef {
	if in == nil {
		return nil
	}
	out := new(ResourceRef)
	in.DeepCopyInto(out)
	return out
}

// --- RemediationPlan ---

func (in *RemediationPlan) DeepCopyInto(out *RemediationPlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *RemediationPlan) DeepCopy() *RemediationPlan {
	if in == nil {
		return nil
	}
	out := new(RemediationPlan)
	in.DeepCopyInto(out)
	return out
}

func (in *RemediationPlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RemediationPlanList) DeepCopyInto(out *RemediationPlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RemediationPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RemediationPlanList) DeepCopy() *RemediationPlanList {
	if in == nil {
		return nil
	}
	out := new(RemediationPlanList)
	in.DeepCopyInto(out)
	return out
}

func (in *RemediationPlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *RemediationPlanSpec) DeepCopyInto(out *RemediationPlanSpec) {
	*out = *in
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]RemediationAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *RemediationPlanSpec) DeepCopy() *RemediationPlanSpec {
	if in == nil {
		return nil
	}
	out := new(RemediationPlanSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *RemediationPlanStatus) DeepCopyInto(out *RemediationPlanStatus) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]ActionResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.StartedAt.DeepCopyInto(&out.StartedAt)
	in.CompletedAt.DeepCopyInto(&out.CompletedAt)
}

func (in *RemediationPlanStatus) DeepCopy() *RemediationPlanStatus {
	if in == nil {
		return nil
	}
	out := new(RemediationPlanStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *RemediationAction) DeepCopyInto(out *RemediationAction) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(ResourceRef)
		**out = **in
	}
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
}

func (in *RemediationAction) DeepCopy() *RemediationAction {
	if in == nil {
		return nil
	}
	out := new(RemediationAction)
	in.DeepCopyInto(out)
	return out
}

func (in *ActionResult) DeepCopyInto(out *ActionResult) {
	*out = *in
	in.ExecutedAt.DeepCopyInto(&out.ExecutedAt)
}

func (in *ActionResult) DeepCopy() *ActionResult {
	if in == nil {
		return nil
	}
	out := new(ActionResult)
	in.DeepCopyInto(out)
	return out
}

// --- OptimizationSuggestion ---

func (in *OptimizationSuggestion) DeepCopyInto(out *OptimizationSuggestion) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *OptimizationSuggestion) DeepCopy() *OptimizationSuggestion {
	if in == nil {
		return nil
	}
	out := new(OptimizationSuggestion)
	in.DeepCopyInto(out)
	return out
}

func (in *OptimizationSuggestion) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OptimizationSuggestionList) DeepCopyInto(out *OptimizationSuggestionList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OptimizationSuggestion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *OptimizationSuggestionList) DeepCopy() *OptimizationSuggestionList {
	if in == nil {
		return nil
	}
	out := new(OptimizationSuggestionList)
	in.DeepCopyInto(out)
	return out
}

func (in *OptimizationSuggestionList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *OptimizationSuggestionSpec) DeepCopyInto(out *OptimizationSuggestionSpec) {
	*out = *in
	out.Scope = in.Scope
	if in.Categories != nil {
		in, out := &in.Categories, &out.Categories
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *OptimizationSuggestionSpec) DeepCopy() *OptimizationSuggestionSpec {
	if in == nil {
		return nil
	}
	out := new(OptimizationSuggestionSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *OptimizationSuggestionStatus) DeepCopyInto(out *OptimizationSuggestionStatus) {
	*out = *in
	if in.Suggestions != nil {
		in, out := &in.Suggestions, &out.Suggestions
		*out = make([]Suggestion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.AnalyzedAt.DeepCopyInto(&out.AnalyzedAt)
}

func (in *OptimizationSuggestionStatus) DeepCopy() *OptimizationSuggestionStatus {
	if in == nil {
		return nil
	}
	out := new(OptimizationSuggestionStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *OptimizationScope) DeepCopyInto(out *OptimizationScope) {
	*out = *in
}

func (in *OptimizationScope) DeepCopy() *OptimizationScope {
	if in == nil {
		return nil
	}
	out := new(OptimizationScope)
	in.DeepCopyInto(out)
	return out
}

func (in *Suggestion) DeepCopyInto(out *Suggestion) {
	*out = *in
	if in.Target != nil {
		in, out := &in.Target, &out.Target
		*out = new(ResourceRef)
		**out = **in
	}
	if in.Current != nil {
		in, out := &in.Current, &out.Current
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Recommended != nil {
		in, out := &in.Recommended, &out.Recommended
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *Suggestion) DeepCopy() *Suggestion {
	if in == nil {
		return nil
	}
	out := new(Suggestion)
	in.DeepCopyInto(out)
	return out
}

// Ensure metav1 import is used
var _ metav1.Time
