apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8ops-metrics
  namespace: k8ops-system
  labels:
    app.kubernetes.io/name: k8ops
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: k8ops
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    honorLabels: true
  jobLabel: app.kubernetes.io/name
