{{- if eq .Values.mode "deployment" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8ops-data
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: k8ops
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
{{- end }}
