apiVersion: v1
kind: Service
metadata:
  name: k8ops-dashboard
  namespace: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: k8ops
spec:
  selector:
    app.kubernetes.io/name: k8ops
  type: {{ .Values.service.type }}
  ports:
  - name: dashboard
    port: {{ .Values.service.port }}
    targetPort: 9090
    protocol: TCP
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
