apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8ops-data
  namespace: k8ops-system
  labels:
    app.kubernetes.io/name: k8ops
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
